workflows:
  build-app:
    name: Build Viby App
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: vHhhIRqP2vuwiDlfj9egw0O_e8EJofoSH9pKLms3
      node: 18.16.0
    scripts:
      - echo "🔧 Installing global CLI tools..."
      - npm install -g expo-cli
      - echo "📦 Installing project dependencies (including eas-cli@^3.19.0)..."
      - npm install
      - echo "🚀 Starting EAS build using local CLI..."
      - npx eas-cli build --platform android --profile production --non-interactive
    artifacts:
      - '**/*.apk'
    publishing:
      email:
        recipients:
          - moataz.elhaddad@gmail.com
        notify:
          success: true
          failure: true
