workflows:
  build-app:
    name: Build Viby App
    max_build_duration: 60
    environment:
      groups:
        - expo-secrets  # this includes your EXPO_TOKEN
      node: 18.16.0
    scripts:
      - echo "🔧 Installing dependencies..."
      - npm install -g expo-cli
      - npm install
      - echo "🚀 Starting Expo build"
      - eas build --platform android --profile production --non-interactive
    artifacts:
      - '**/*.apk'
    publishing:
      email:
        recipients:
          - moataz.elhaddad@gmail.com
        notify:
          success: true
          failure: true
