workflows:
  build-app:
    name: Build Viby App
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: syW2zv-kMs6HwlwkW9kjcBWwFssaZOsQLPS9uM54
      node: 18.16.0
    scripts:
      - echo "🔧 Installing CLI tools"
      - npm install -g expo-cli eas-cli
      - echo "📦 Installing project dependencies"
      - npm install
      - echo "🚀 Running EAS Build"
      - eas build --platform android --profile production --non-interactive
    artifacts:
      - '**/*.apk'
    publishing:
      email:
        recipients:
          - moataz.elhaddad@gmail.com
        notify:
          success: true
          failure: true
